# This file was generated by GoReleaser. DO NOT EDIT.
cask "doctier" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "926f07bd2424ceec6e3f139aac858b5b28f73c181aba12846f1d72facaecd1cc"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e3469b5cefd53f45fdf4620b0108e7df3641df0fbe803fb797324e44e3a5dad4"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd72c3c5b14e3a2ba3f8e5d0dfb728cc24dc94f58d903157ea44d884f77d4e12"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "175fdd5ff0f178cd1375192e501b8e4872bf235338050b63c5a32eec246c17e3"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "doctier"
  desc "Tiered privacy and lifecycle for generated documents, over git."
  homepage "https://github.com/RubenGlez/doctier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doctier"

  # No zap stanza required

end
