# This file was generated by GoReleaser. DO NOT EDIT.
cask "doctier" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "23a42fb4b4fad7ff80df3ecb9627c429aa08967bb3d59bd6cb9f8b59208acacb"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "49771787add010b2f68c9900a4eb1e98ce41c70763b63343dcb0855f98c07d3b"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a61cd4334133a74e3b73bf523173f79904697d5bb66bdc00f375c0f708bfaa4a"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2dfeb1212fc26956180b464baf07a34a251e44c9d6d2d2a76472453b50787b81"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_linux_arm64.tar.gz"
    end
  end

  name "doctier"
  desc "Tiered privacy and lifecycle for generated documents, over git."
  homepage "https://github.com/RubenGlez/doctier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doctier"

  # No zap stanza required

end
