# This file was generated by GoReleaser. DO NOT EDIT.
cask "doctier" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "c457edf4da076c386b66a1dbf218ce9eaf5f9b508a960495d6fd0d57653167ba"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d7f785ec356a5967bb11d2fa31c2e88fe6a7485b37410ea02173bce850a909d"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d297a15b2a46934ed228b830e57a304523d9704b230bb2c0c6ca11f899f33877"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "de35c01cbdd9c7cf82c9bf57b5efaea61e042d44fd7317cf9d27120bb0ab3dee"
      url "https://github.com/RubenGlez/doctier/releases/download/v#{version}/doctier_#{version}_linux_amd64.tar.gz"
    end
  end

  name "doctier"
  desc "Tiered privacy and lifecycle for generated documents, over git."
  homepage "https://github.com/RubenGlez/doctier"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "doctier"

  # No zap stanza required
end
